apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
  labels:
    app: tenant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: alvinwidi33/tenant-service:latest  # Pastikan image ada di Docker Hub
          ports:
            - containerPort: 8003
          env:
            - name: TENANT_ID
              value: "47dd6b24-0b23-46b0-a662-776158d089ba"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-service.default.svc.cluster.local"
            - name: DB_HOST
              value: "database-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "tenant"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  selector:
    app: tenant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: ClusterIP
