apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: my-products-image:latest  
          ports:
            - containerPort: 8002
          env:
            - name: TENANT_ID
              value: "47dd6b24-0b23-46b0-a662-776158d089ba"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-service.default.svc.cluster.local"
            - name: PRODUCT_MS_URL
              value: "http://products-service.default.svc.cluster.local"
            - name: TENANT_MS_URL
              value: "http://tenant-service.default.svc.cluster.local"
            - name: ADMIN_JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "products"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "products"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
