apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: wishlist
          image: alvinwidi33/wishlist:latest 
          ports:
            - containerPort: 8004
          env:
            - name: WISHLIST_ID
              value: "47dd6b24-0b23-46b0-a662-776158d089ba"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: ADMIN_JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-service.default.svc.cluster.local"
            - name: PRODUCT_MS_URL
              value: "http://products-service.default.svc.cluster.local"
            - name: DB_HOST
              value: "database-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "wishlist"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
spec:
  selector:
    app: wishlist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
  type: ClusterIP
