name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 🔹 Login ke Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 🔹 Build & Push Authentication Service
      - name: Build & Push Authentication Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest authentication/.
          docker push ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest
